# Generated by Django 5.0.14 on 2026-05-11 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_prontuario_consulta_remove_prontuario_medico_and_more'),
        ('appointments', '0002_alter_consulta_options_alter_consulta_medico_and_more'),
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prontuario',
            options={'ordering': ['-data_registro'], 'verbose_name': 'prontuário', 'verbose_name_plural': 'prontuários'},
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='consulta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.consulta'),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.medico'),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.paciente'),
        ),
    ]
