# Generated by Django 5.0.14 on 2026-05-11 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_especialidade_options_alter_medico_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prontuario',
            name='consulta',
        ),
        migrations.RemoveField(
            model_name='prontuario',
            name='medico',
        ),
        migrations.RemoveField(
            model_name='prontuario',
            name='paciente',
        ),
        migrations.AlterField(
            model_name='medico',
            name='especialidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.especialidade'),
        ),
        migrations.DeleteModel(
            name='Consulta',
        ),
        migrations.DeleteModel(
            name='Prontuario',
        ),
    ]
